version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: caas_agriculture
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: caas_agriculture_db
      MYSQL_USER: zona
      MYSQL_PASSWORD: caas_zona_103012430010
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: